language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t alexioan87/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true alexioan87/react-test npm test 

after_success:
  - docker build -t alexioan87/multi-client ./client
  - docker build -t alexioan87/multi-nginx ./nginx
  - docker build -t alexioan87/multi-server ./server
  - docker build -t alexioan87/multi-worker ./worker
  # Login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push alexioan87/multi-client
  - docker push alexioan87/multi-nginx
  - docker push alexioan87/multi-server
  - docker push alexioan87/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-025063817354
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY